name: Build Python Artifacts

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove obsolete pathlib
        run: |
          python -m pip uninstall -y pathlib

      - name: Build Executable on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile gui.py
          mv dist/gui dist/gui_linux

      - name: Build Executable on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile gui.py
          mv dist/gui dist/gui_mac

      - name: Build Executable on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile gui.py
          Move-Item -Path dist\gui.exe -Destination dist\gui_windows.exe
        shell: powershell

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts-${{ matrix.os }}
          path: dist/

  # upload-release-assets:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Download Artifacts (Ubuntu)
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-artifacts-ubuntu-latest
  #         path: ./artifacts/ubuntu

  #     - name: Download Artifacts (MacOS)
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-artifacts-macos-latest
  #         path: ./artifacts/macos

  #     - name: Download Artifacts (Windows)
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-artifacts-windows-latest
  #         path: ./artifacts/windows

  #     - name: Upload Release Assets
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ github.event.release.upload_url }}
  #         asset_path: ./artifacts/ubuntu/**
  #         asset_name: python-artifacts-ubuntu-latest.zip
  #         asset_content_type: application/zip
  #     - uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ github.event.release.upload_url }}
  #         asset_path: ./artifacts/macos/**
  #         asset_name: python-artifacts-macos-latest.zip
  #         asset_content_type: application/zip
  #     - uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ github.event.release.upload_url }}
  #         asset_path: ./artifacts/windows/**
  #         asset_name: python-artifacts-windows-latest.zip
  #         asset_content_type: application/zip
