name: Build and Release Python Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Build and Release
        uses: kentsx/Python2Exe@v1.1.1
        with:
          main: gui
          exe_name: 'CK3_Mod_Tool'
          icon: 'icon.ico'  # Replace with your icon path if you have one
          artifact: true
          release: true
          token: ${{ secrets.GITHUB_TOKEN }}
          no-console: true
          use-dependencies: true
          compression_level: 6